name: Botanis
on: 
  push:
    branches: [ main ]
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        # https://github.com/actions/checkout
        - name: git-checkout
          uses: actions/checkout@v2
        - name: Set up our JDK environment
          uses: actions/setup-java@v1.4.3
          with:
            java-version: 1.8
        - name: build Apk
          id: buildAPK
          uses: eskatos/gradle-command-action@v1.3.3
          with:
            gradle-version: current
            wrapper-cache-enabled: true
            dependencies-cache-enabled: true
            configuration-cache-enabled: true
            arguments: assembleRelease
        # Tests should happend here
        #- name: Sign apk
        #  id: signApk
        #  uses: r0adkll/sign-android-release@v1.0.1
        #  with:
        #    releaseDirectory: app/build/outputs/apk/ourbuildtype/release
            #alias: ${{ secrets.KEYALIAS }}
            #signingKeyBase64: ${{ secrets.KEYSTORE }}
            #keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
            #keyPassword: ${{ secrets.KEY_PASSWORD }}
        - name: Upload APK
          uses: actions/upload-artifact@v2.2.0
          with:
            name: Release artifact
            path: app/build/outputs/apk/dev/app-artifact-*.apk
