name: Botanist
on: 
  push:
    branches: [ main ]
jobs:
  APK:
      name: Generate APK
      runs-on: ubuntu-latest
      steps:
        # https://github.com/actions/checkout
        - name: git-checkout
          uses: actions/checkout@v2
        - name: Set up JDK environment
          uses: actions/setup-java@v2.5.0
          with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '11'
        - name: Set execution flag for gradlew
          run: chmod +x gradlew
        - name: Build APK
          run: bash ./gradlew assembleDebug --stacktrace
        - name: Upload APK
          uses: actions/upload-artifact@v1
          with:
            name: apk
            path: app/build/outputs/apk/debug/app-debug.apk
       
