name: CI Build and Release
on:
  push:
        tags:
        - 'v*'
  workflow_run:
    workflows: ["Code Checkstyle"]
    types:
      - completed
jobs:
  BuildDebugApk:
      name: Generate Debug APK
      runs-on: ubuntu-latest
      steps:
        # https://github.com/actions/checkout
        - name: git-checkout
          uses: actions/checkout@v2
        - name: Set up JDK environment
          uses: actions/setup-java@v2.5.0
          with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '11'
        - name: Set execution flag for gradlew
          run: chmod +x gradlew
        - name: Build Debug APK
          run: bash ./gradlew assembleDebug --stacktrace
          
  UploadDebugApk:    
      name: Upload Debug APK
      needs: BuildDebugApk
      runs-on: ubuntu-latest
      steps:
        - name: Upload_APK
          uses: actions/upload-artifact@v3.0.0
          with:
            name: debug
            path: app/build/outputs/apk/debug/app-debug.apk

  BuildReleaseApk:
        name: Build Release APK
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/v')
        steps:
          - name: git-checkout
            uses: actions/checkout@v2
          - name: Set up JDK environment
            uses: actions/setup-java@v2.5.0
            with:
              distribution: 'zulu' # See 'Supported distributions' for available options
              java-version: '11'
          - name: Set execution flag for gradlew
            run: chmod +x gradlew
          - name: Build Debug APK
            run: bash ./gradlew assembleRelease --stacktrace
  
  UploadReleaseApk:    
      name: Upload Release APK
      needs: BuildReleaseApk
      runs-on: ubuntu-latest
      steps:
        - name: Upload_APK
          uses: actions/upload-artifact@v3.0.0
          with:
            name: release_APK
            path: app/build/outputs/apk/release/app-release.apk

  Sign:
    name: Sign Release Apk
    needs: UploadReleaseApk
    runs-on: ubuntu-latest
    steps:
      - name: Sign artifact
        id: signArtifact
        uses: r0adkll/sign-android-release@v1.0.1
        with:
          releaseDirectory: app/build/outputs/apk/release
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload our APK
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Release artifact
          path: app/build/outputs/apk/release/app-release.apk
       
