# This is a basic workflow to help you get started with Actions

name: CI Create Signed Release

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# decode our saved and encoded Keystore file
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sign artifact
        id: signArtifact
        uses: r0adkll/sign-android-release@v1.0.1
        with:
          releaseDirectory: app/build/outputs/apk/ourbuildtype/release
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload our APK
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Release artifact
          path: app/build/outputs/apk/ourbuildtype/release/app-artifact-*.apk
